version: "3.8"
services:
  backend-server:
    build: .
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.0"
    platform: linux/x86_64
    container_name: MysqlDB
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ecommerce_oil
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
      MYSQL_ROOT_PASSWORD: admin@123